#internal_service
hostInternal: localhost
portInternal: 8080

#device_service
hostDevice: localhost
portDevice: 8088

#jwt_token_setting
jwtToken:
  secret: "qwerty"
  issuer: "ots"
  expiresAt: "24h0m0s"

#postgres_setting
postgreSQL:
  user: "postgres"
  password: "postgres"
  bdName: "postgres"
  sslMode: "disable"
  host: "localhost"
  port: "5432"